package com.thescar.dnd.datagen;

import com.thescar.dnd.DnD;
import com.thescar.dnd.block.ModBlocks;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.tags.BlockTags;
import net.minecraftforge.common.data.BlockTagsProvider;
import net.minecraftforge.common.data.ExistingFileHelper;
import org.jetbrains.annotations.Nullable;

import java.util.concurrent.CompletableFuture;

public class ModBlockTagGenerator extends BlockTagsProvider {
    public ModBlockTagGenerator(PackOutput output, CompletableFuture<HolderLookup.Provider> lookupProvider, @Nullable ExistingFileHelper existingFileHelper) {
        super(output, lookupProvider, DnD.MOD_ID, existingFileHelper);
    }

    @Override
    protected void addTags(HolderLookup.Provider pProvider) {
        this.tag(BlockTags.MINEABLE_WITH_PICKAXE)
                .add(ModBlocks.RAW_ADAMANTITE_BLOCK.get(),
                        ModBlocks.ADAMANTITE_ORE.get(),
                        ModBlocks.DEEPSLATE_ADAMANTITE_ORE.get(),

                        ModBlocks.SHALE.get(),
                        ModBlocks.SHALE_WALL.get(),
                        ModBlocks.SHALE_SLAB.get(),
                        ModBlocks.SHALE_STAIRS.get(),
                        ModBlocks.POLISHED_SHALE.get(),
                        ModBlocks.POLISHED_SHALE_WALL.get(),
                        ModBlocks.POLISHED_SHALE_SLAB.get(),
                        ModBlocks.POLISHED_SHALE_STAIRS.get(),
                        ModBlocks.SHALE_BRICKS.get(),
                        ModBlocks.SHALE_BRICK_WALL.get(),
                        ModBlocks.SHALE_BRICK_SLAB.get(),
                        ModBlocks.SHALE_BRICK_STAIRS.get(),
                        ModBlocks.SHALE_PILLAR.get(),
                        ModBlocks.SHALE_SHINGLES.get(),
                        ModBlocks.SHALE_SHINGLE_WALL.get(),
                        ModBlocks.SHALE_SHINGLE_SLAB.get(),
                        ModBlocks.SHALE_SHINGLE_STAIRS.get(),
                        ModBlocks.SHALE_TILES.get(),
                        ModBlocks.SHALE_TILE_WALL.get(),
                        ModBlocks.SHALE_TILE_SLAB.get(),
                        ModBlocks.SHALE_TILE_STAIRS.get(),

                        ModBlocks.GREENSCHIST.get(),
                        ModBlocks.GREENSCHIST_WALL.get(),
                        ModBlocks.GREENSCHIST_SLAB.get(),
                        ModBlocks.GREENSCHIST_STAIRS.get(),
                        ModBlocks.POLISHED_GREENSCHIST.get(),
                        ModBlocks.POLISHED_GREENSCHIST_WALL.get(),
                        ModBlocks.POLISHED_GREENSCHIST_SLAB.get(),
                        ModBlocks.POLISHED_GREENSCHIST_STAIRS.get(),
                        ModBlocks.GREENSCHIST_BRICKS.get(),
                        ModBlocks.GREENSCHIST_BRICK_WALL.get(),
                        ModBlocks.GREENSCHIST_BRICK_SLAB.get(),
                        ModBlocks.GREENSCHIST_BRICK_STAIRS.get(),
                        ModBlocks.GREENSCHIST_PILLAR.get(),
                        ModBlocks.CHISELED_GREENSCHIST.get(),
                        ModBlocks.ALGAL_GREENSCHIST_BRICKS.get(),
                        ModBlocks.ALGAL_GREENSCHIST_BRICK_WALL.get(),
                        ModBlocks.ALGAL_GREENSCHIST_BRICK_SLAB.get(),
                        ModBlocks.ALGAL_GREENSCHIST_BRICK_STAIRS.get(),

                        ModBlocks.AGING_ADOBE.get(),
                        ModBlocks.AGING_ADOBE_WALL.get(),
                        ModBlocks.AGING_ADOBE_SLAB.get(),
                        ModBlocks.AGING_ADOBE_STAIRS.get(),
                        ModBlocks.AGING_ADOBE_PILLAR.get(),
                        ModBlocks.CHISELED_AGING_ADOBE.get(),
                        ModBlocks.CRACKED_AGING_ADOBE.get(),
                        ModBlocks.CRACKED_AGING_ADOBE_WALL.get(),
                        ModBlocks.CRACKED_AGING_ADOBE_SLAB.get(),
                        ModBlocks.CRACKED_AGING_ADOBE_STAIRS.get(),
                        ModBlocks.MOSSY_AGING_ADOBE.get(),
                        ModBlocks.MOSSY_AGING_ADOBE_WALL.get(),
                        ModBlocks.MOSSY_AGING_ADOBE_SLAB.get(),
                        ModBlocks.MOSSY_AGING_ADOBE_STAIRS.get(),
                        ModBlocks.PAINTED_AGING_ADOBE.get(),
                        ModBlocks.SANDY_AGING_ADOBE.get(),
                        ModBlocks.SANDY_AGING_ADOBE_WALL.get(),
                        ModBlocks.SANDY_AGING_ADOBE_SLAB.get(),
                        ModBlocks.SANDY_AGING_ADOBE_STAIRS.get(),

                        ModBlocks.RAW_IRONSTONE.get(),
                        ModBlocks.RAW_IRONSTONE_WALL.get(),
                        ModBlocks.RAW_IRONSTONE_SLAB.get(),
                        ModBlocks.RAW_IRONSTONE_STAIRS.get(),
                        ModBlocks.IRONSTONE_PILLAR.get(),
                        ModBlocks.POLISHED_IRONSTONE.get(),
                        ModBlocks.POLISHED_IRONSTONE_WALL.get(),
                        ModBlocks.POLISHED_IRONSTONE_SLAB.get(),
                        ModBlocks.POLISHED_IRONSTONE_STAIRS.get(),
                        ModBlocks.IRONSTONE_BRICKS.get(),
                        ModBlocks.IRONSTONE_BRICK_WALL.get(),
                        ModBlocks.IRONSTONE_BRICK_SLAB.get(),
                        ModBlocks.IRONSTONE_BRICK_STAIRS.get(),
                        ModBlocks.MOSSY_IRONSTONE_BRICKS.get(),
                        ModBlocks.MOSSY_IRONSTONE_BRICK_WALL.get(),
                        ModBlocks.MOSSY_IRONSTONE_BRICK_SLAB.get(),
                        ModBlocks.MOSSY_IRONSTONE_BRICK_STAIRS.get(),
                        ModBlocks.CRACKED_IRONSTONE_BRICKS.get(),
                        ModBlocks.CRACKED_IRONSTONE_BRICK_WALL.get(),
                        ModBlocks.CRACKED_IRONSTONE_BRICK_SLAB.get(),
                        ModBlocks.CRACKED_IRONSTONE_BRICK_STAIRS.get(),
                        ModBlocks.CHISELED_IRONSTONE.get(),
                        ModBlocks.IRONSTONE_TILES.get(),
                        ModBlocks.IRONSTONE_TILE_WALL.get(),
                        ModBlocks.IRONSTONE_TILE_SLAB.get(),
                        ModBlocks.IRONSTONE_TILE_STAIRS.get(),
                        ModBlocks.IRONSTONE_BATTLEMENT.get(),

                        ModBlocks.FORGED_BRICKS.get(),
                        ModBlocks.FORGED_BRICK_WALL.get(),
                        ModBlocks.FORGED_BRICK_SLAB.get(),
                        ModBlocks.FORGED_BRICK_STAIRS.get(),
                        ModBlocks.CRACKED_FORGED_BRICKS.get(),
                        ModBlocks.CRACKED_FORGED_BRICK_WALL.get(),
                        ModBlocks.CRACKED_FORGED_BRICK_SLAB.get(),
                        ModBlocks.CRACKED_FORGED_BRICK_STAIRS.get(),
                        ModBlocks.LINED_FORGED_BRICKS.get(),
                        ModBlocks.LINED_FORGED_BRICK_WALL.get(),
                        ModBlocks.LINED_FORGED_BRICK_SLAB.get(),
                        ModBlocks.LINED_FORGED_BRICK_STAIRS.get(),
                        ModBlocks.FORGED_PILLAR.get(),
                        ModBlocks.FORGED_TILES.get(),
                        ModBlocks.FORGED_TILE_WALL.get(),
                        ModBlocks.FORGED_TILE_SLAB.get(),
                        ModBlocks.FORGED_TILE_STAIRS.get(),

                        ModBlocks.LAVAROCK.get(),
                        ModBlocks.LAVAROCK_WALL.get(),
                        ModBlocks.LAVAROCK_SLAB.get(),
                        ModBlocks.LAVAROCK_STAIRS.get(),
                        ModBlocks.LAVAROCK_BRICK_WALL.get(),
                        ModBlocks.LAVAROCK_BRICKS.get(),
                        ModBlocks.LAVAROCK_BRICK_SLAB.get(),
                        ModBlocks.LAVAROCK_BRICK_STAIRS.get(),
                        ModBlocks.CRACKED_LAVAROCK_BRICKS.get(),
                        ModBlocks.CRACKED_LAVAROCK_BRICK_WALL.get(),
                        ModBlocks.CRACKED_LAVAROCK_BRICK_SLAB.get(),
                        ModBlocks.CRACKED_LAVAROCK_BRICK_STAIRS.get(),
                        ModBlocks.CHARRED_LAVAROCK_BRICKS.get(),
                        ModBlocks.CHARRED_LAVAROCK_BRICK_WALL.get(),
                        ModBlocks.CHARRED_LAVAROCK_BRICK_SLAB.get(),
                        ModBlocks.CHARRED_LAVAROCK_BRICK_STAIRS.get(),
                        ModBlocks.POLISHED_LAVAROCK.get(),
                        ModBlocks.POLISHED_LAVAROCK_WALL.get(),
                        ModBlocks.POLISHED_LAVAROCK_SLAB.get(),
                        ModBlocks.POLISHED_LAVAROCK_STAIRS.get(),
                        ModBlocks.CHISELED_LAVAROCK.get(),
                        ModBlocks.LAVAROCK_PILLAR.get(),

                        ModBlocks.SHINGLES.get(),
                        ModBlocks.SHINGLE_WALL.get(),
                        ModBlocks.SHINGLE_SLAB.get(),
                        ModBlocks.SHINGLE_STAIRS.get(),
                        ModBlocks.RUINED_SHINGLES.get(),
                        ModBlocks.RUINED_SHINGLE_WALL.get(),
                        ModBlocks.RUINED_SHINGLE_SLAB.get(),
                        ModBlocks.RUINED_SHINGLE_STAIRS.get());


        this.tag(BlockTags.MINEABLE_WITH_SHOVEL)
                .add(ModBlocks.RUBBLE.get(),
                        ModBlocks.CHUNKY_RUBBLE.get());

        this.tag(BlockTags.NEEDS_IRON_TOOL)
                .add(ModBlocks.RAW_ADAMANTITE_BLOCK.get(),
                        ModBlocks.ADAMANTITE_ORE.get(),
                        ModBlocks.DEEPSLATE_ADAMANTITE_ORE.get(),
                        ModBlocks.SHALE.get(),
                        ModBlocks.POLISHED_SHALE.get(),
                        ModBlocks.SHALE_BRICKS.get(),
                        ModBlocks.SHALE_PILLAR.get(),
                        ModBlocks.SHALE_SHINGLES.get(),
                        ModBlocks.SHALE_TILES.get(),
                        ModBlocks.GREENSCHIST.get(),
                        ModBlocks.GREENSCHIST_BRICKS.get(),
                        ModBlocks.GREENSCHIST_PILLAR.get());

        this.tag(BlockTags.WALLS)
                .add(ModBlocks.SHALE_WALL.get(),
                        ModBlocks.SHALE_WALL.get(),
                        ModBlocks.POLISHED_SHALE_WALL.get(),
                        ModBlocks.SHALE_BRICK_WALL.get(),
                        ModBlocks.SHALE_SHINGLE_WALL.get(),
                        ModBlocks.SHALE_TILE_WALL.get(),
                        ModBlocks.GREENSCHIST_WALL.get(),
                        ModBlocks.POLISHED_GREENSCHIST_WALL.get(),
                        ModBlocks.GREENSCHIST_BRICK_WALL.get(),
                        ModBlocks.ALGAL_GREENSCHIST_BRICK_WALL.get(),
                        ModBlocks.AGING_ADOBE_WALL.get(),
                        ModBlocks.CRACKED_AGING_ADOBE_WALL.get(),
                        ModBlocks.MOSSY_AGING_ADOBE_WALL.get(),
                        ModBlocks.SANDY_AGING_ADOBE_WALL.get(),
                        ModBlocks.RAW_IRONSTONE_WALL.get(),
                        ModBlocks.POLISHED_IRONSTONE_WALL.get(),
                        ModBlocks.IRONSTONE_BRICK_WALL.get(),
                        ModBlocks.MOSSY_IRONSTONE_BRICK_WALL.get(),
                        ModBlocks.CRACKED_IRONSTONE_BRICK_WALL.get(),
                        ModBlocks.IRONSTONE_TILE_WALL.get(),
                        ModBlocks.FORGED_BRICK_WALL.get(),
                        ModBlocks.CRACKED_FORGED_BRICK_WALL.get(),
                        ModBlocks.LINED_FORGED_BRICK_WALL.get(),
                        ModBlocks.FORGED_TILE_WALL.get(),
                        ModBlocks.LAVAROCK_WALL.get(),
                        ModBlocks.LAVAROCK_BRICK_WALL.get(),
                        ModBlocks.CRACKED_LAVAROCK_BRICK_WALL.get(),
                        ModBlocks.CHARRED_LAVAROCK_BRICK_WALL.get(),
                        ModBlocks.POLISHED_LAVAROCK_WALL.get(),
                        ModBlocks.SHINGLE_WALL.get(),
                    (ModBlocks.RUINED_SHINGLE_WALL.get()));
    }
}